### ISSUE TITLE
Jérome: Scriptable object fonction-il dans les applications publiées

### ISSUE THREAD

**Issue by JamsCenter** [JamsCenter/2017_10_16_UnityStarterPack#1]
Scriptable object fonction-il dans les applications publiées

**Comment by JeromeJ** [comment]
https://answers.unity.com/questions/835458/saving-a-scriptableobject-asset-on-android.html

Pas par défaut il semblerait :(

À essayer: `AssetDatabase.CreateAsset`

**Comment by JamsCenter** [comment]
- https://answers.unity.com/questions/896298/savingloading-scriptableobject-during-runtime.html
- "No, you can't. The ScriptableObject is actually only useful at edit time. At runtime it's as useful as a bag of bricks. "  Source: https://answers.unity.com/questions/831285/can-you-use-a-serializedobject-to-save-game-state.html
